version: '3.9'
services:
    canronglan:
        image: 'ghcr.io/canronglan/3x-ui:latest'
        restart: unless-stopped
        privileged: true
        network_mode: host
        environment:
            - ID=4
            - HOST=alisgp
            - XRAY_VMESS_AEAD_FORCED=false
        hostname: alisgp
        container_name: 3x-ui-alan
        volumes:
            - $PWD/db/:/etc/x-ui/
            - $PWD/cert/:/root/cert/

