version: '3.9'
services:
    canronglan:
        image: 'ghcr.io/canronglan/3x-ui:latest'
        restart: unless-stopped
        privileged: true
        network_mode: host
        environment:
            - ID=5
            - HOST=lisaus1
            - XRAY_VMESS_AEAD_FORCED=false
            - NPS_SERVER=sgnat1.biaotee.top
            - VKEY=mrhb35juihx1m79p
        container_name: 3x-ui-alan
        volumes:
            - $PWD/db/:/etc/x-ui/
            - $PWD/cert/:/root/cert/
            - $PWD/nps/:/app/nps/
            - $PWD/npc/:/app/npc/
